# Generated by Django 4.1.5 on 2023-02-23 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='menteelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentee_name', models.CharField(max_length=100)),
                ('mentee_email', models.CharField(max_length=100)),
                ('mentee_password', models.CharField(max_length=100)),
                ('mentee_dob', models.CharField(default='dd/mm/yyyy', max_length=15)),
                ('mentee_age', models.IntegerField(default=0)),
                ('mentee_bg', models.CharField(default='0', max_length=5)),
                ('mentee_relegion', models.CharField(default='0', max_length=10)),
                ('mentee_caste', models.CharField(default='0', max_length=10)),
                ('mentee_parish', models.CharField(default='Nil', max_length=20)),
                ('mentee_paddress', models.CharField(default='0', max_length=200)),
                ('mentee_caddress', models.CharField(default='0', max_length=200)),
                ('mentee_mob', models.IntegerField(default=0)),
                ('mentee_tel', models.IntegerField(default=0)),
                ('father_name', models.CharField(default='0', max_length=20)),
                ('father_profession', models.CharField(default='0', max_length=20)),
                ('father_age', models.IntegerField(default=0)),
                ('father_placeofwork', models.CharField(default='0', max_length=10)),
                ('father_mob', models.IntegerField(default=0)),
                ('mother_name', models.CharField(default='0', max_length=20)),
                ('mother_profession', models.CharField(default='0', max_length=20)),
                ('mother_age', models.IntegerField(default=0)),
                ('mother_placeofwork', models.CharField(default='0', max_length=10)),
                ('mother_mob', models.IntegerField(default=0)),
                ('brother_or_sister_std', models.CharField(default='Nil', max_length=20)),
                ('position_in_family', models.CharField(default='0', max_length=10)),
                ('local_guardian_name', models.CharField(default='0', max_length=20)),
                ('local_guardian_profession', models.CharField(default='0', max_length=20)),
                ('local_guardian_age', models.IntegerField(default=0)),
                ('local_guardian_mob', models.IntegerField(default=0)),
                ('local_guardian_address', models.CharField(default='0', max_length=100)),
                ('hostelornot', models.CharField(default='0', max_length=5)),
                ('if_hostel_freqencyvisithome', models.CharField(default='0', max_length=15)),
                ('mode_of_convayence', models.CharField(default='0', max_length=20)),
                ('entrance_rank', models.IntegerField(default=0)),
                ('work_experience', models.CharField(default='0', max_length=50)),
                ('extra_curricular', models.CharField(default='0', max_length=50)),
                ('language_proficiency', models.CharField(default='0', max_length=50)),
                ('other_acheivements', models.CharField(default='0', max_length=50)),
                ('personal_goal', models.CharField(default='0', max_length=20)),
                ('professional_goal', models.CharField(default='0', max_length=20)),
                ('social_goal', models.CharField(default='0', max_length=10)),
                ('strength', models.CharField(default='0', max_length=30)),
                ('weakness', models.CharField(default='0', max_length=30)),
                ('oppertunity', models.CharField(default='0', max_length=50)),
                ('threats', models.CharField(default='0', max_length=25)),
                ('hobbies', models.CharField(default='0', max_length=25)),
                ('rolemodel', models.CharField(default='0', max_length=100)),
                ('first_impression', models.CharField(default='0', max_length=20)),
                ('source_of_income', models.CharField(default='0', max_length=20)),
                ('Economic_background', models.CharField(default='Fine', max_length=20)),
                ('perental_harmony', models.CharField(default='0', max_length=50)),
                ('relationship_with_family', models.CharField(default='0', max_length=25)),
                ('atmosphere_at_home_for_study', models.CharField(default='good', max_length=25)),
                ('relegious_life', models.CharField(default='0', max_length=20)),
                ('social_outlook', models.CharField(default='0', max_length=20)),
                ('read_habit', models.CharField(default='0', max_length=20)),
                ('behaviour', models.CharField(default='good', max_length=20)),
                ('potential', models.CharField(default='0', max_length=20)),
                ('weakness_of_mentee', models.CharField(default='0', max_length=25)),
                ('adjustment_to_college', models.CharField(default='good', max_length=25)),
                ('addiction', models.CharField(default='Nil', max_length=25)),
                ('improvement_area', models.CharField(default='0', max_length=20)),
                ('specific_concern', models.CharField(default='0', max_length=20)),
                ('referal_to_language_lab', models.CharField(default='0', max_length=10)),
                ('fitness_for_MCA', models.CharField(default='0', max_length=20)),
                ('life_goals', models.CharField(default='0', max_length=20)),
                ('core_competency', models.CharField(default='Nil', max_length=20)),
                ('intercollege_representation', models.CharField(default='0', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='mentor',
            fields=[
                ('mentor_name', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('mentor_email', models.CharField(max_length=40)),
                ('mentor_password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='mentee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentee_name', models.CharField(max_length=100)),
                ('mentor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.mentor')),
            ],
        ),
    ]
