# Generated by Django 4.1.7 on 2023-02-24 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='counselling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('suggestion', models.CharField(max_length=250)),
                ('technical_assessment', models.CharField(max_length=200)),
                ('interpersonal_assessment', models.CharField(max_length=200)),
                ('communication_assessment', models.CharField(max_length=200)),
                ('leadership_assessment', models.CharField(max_length=200)),
                ('improvement_suggestion', models.CharField(max_length=200)),
                ('mentee_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.mentee')),
                ('mentor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.mentor')),
            ],
        ),
        migrations.CreateModel(
            name='assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_name', models.CharField(max_length=100)),
                ('feedback', models.CharField(max_length=250)),
                ('mentee_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.mentee')),
                ('mentor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.mentor')),
            ],
        ),
        migrations.CreateModel(
            name='accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_duration', models.DurationField()),
                ('Reason_for_stay', models.CharField(max_length=250)),
                ('stay_by_sjcet_or_not', models.CharField(max_length=10)),
                ('Details', models.CharField(max_length=250)),
                ('mentee_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.mentee')),
            ],
        ),
        migrations.CreateModel(
            name='academicqualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=50)),
                ('college_name', models.CharField(max_length=200)),
                ('university_name', models.CharField(max_length=50)),
                ('mark', models.IntegerField()),
                ('medium_of_instruction', models.CharField(max_length=50)),
                ('mentee_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.mentee')),
            ],
        ),
    ]
